[package]
name = "wyrd-clipboard"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wyrd-clipboard"
path = "src/main.rs"

[dependencies]
tokio                 = { workspace = true }
wayland-client        = { workspace = true }
wayland-protocols-wlr = { workspace = true }
serde                 = { workspace = true }
serde_json            = { workspace = true }
anyhow                = { workspace = true }
log                   = { workspace = true }
env_logger            = { workspace = true }
clap                  = { workspace = true }
libc                  = { workspace = true }
