[package]
name = "wyrd-module-clock"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wyrd-module-sdk = { workspace = true }
chrono = { version = "0.4", default-features = false, features = ["alloc"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
