name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: wasm32-unknown-unknown

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev libxkbcommon-dev libfontconfig1-dev libpulse-dev

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Cargo check workspace
        run: cargo check --workspace

      - name: Run workspace tests
        run: cargo test --workspace --verbose

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
